# TraceMe
# config.yml
---
documentation:
  description: |
    Test new version of TraceMe and run traceability analysis 

  authors:
    - zhou_jian

datasets:
  - {model: ACCESS-ESM1-5, exp: historical, ensemble: r1i1p1,  start_year: 2015,  end_year: 2100}
  - {model: BCC-CSM2-MR,   exp: historical, ensemble: r1i1p1,  start_year: 2015,  end_year: 2100}
  - {model: CanESM5,       exp: historical, ensemble: r1i1p1,  start_year: 2015,  end_year: 2100}
  - {model: CESM2,         exp: historical, ensemble: r1i1p1,  start_year: 2015,  end_year: 2100}
  - {model: CNRM-ESM2-1,   exp: historical, ensemble: r1i1p1,  start_year: 2015,  end_year: 2100}
  - {model: EC-Earth3-Veg, exp: historical, ensemble: r1i1p1,  start_year: 2015,  end_year: 2100}
  - {model: IPSL-CM6A-LR,  exp: historical, ensemble: r1i1p1,  start_year: 2015,  end_year: 2100}
  - {model: MIROC-ES2L,    exp: historical, ensemble: r1i1p1,  start_year: 2015,  end_year: 2100}

variables:
  - {name: cCwd,    frequency: month, unit: kg m-2}
  - {name: cLitter, frequency: month, unit: kg m-2}
  - {name: cSoil,   frequency: month, unit: kg m-2}
  - {name: cVeg,    frequency: month, unit: kg m-2}
  - {name: npp,     frequency: month, unit: kg m-2 s-1}
  - {name: gpp,     frequency: month, unit: kg m-2 s-1}
  - {name: tas,     frequency: month, unit: K}
  - {name: pr,      frequency: month, unit: kg m-2 s-1}

region:
  latmin: -90
  latmax: 90
  lonmin: -180
  lonmax: 180

path:
  inputDir: /mnt/c/Users/jzhou/Documents/TraceMe_offline/dataSource/ssp126 #/mnt/i/TraceMe/dataSources/Model/download/historical #/mnt/e/MyWorks/traceME_offline/inputData 
  workRoot: /mnt/c/Users/jzhou/Documents/TraceMe_offline/TraceMe_workdir_ssp126 #/mnt/f/ubuntu/Works/TraceMe/TraceMe_workdir #/mnt/e/MyWorks/traceME_offline/TraceMe_workdir

script:
  TraceMeLand 