# TraceMe
# config.yml
---
documentation:
  description: |
    Test new version of TraceMe and run traceability analysis 

  authors:
    - zhou_jian

datasets:
  - {model: CABLE-POP, exp: historical, ensemble: r1i1p1,  start_year: 1700,  end_year: 2019}
  - {model: CLASSIC,   exp: historical, ensemble: r1i1p1,  start_year: 1700,  end_year: 2019}
  - {model: CLM5,       exp: historical, ensemble: r1i1p1,  start_year: 1700,  end_year: 2019}
  - {model: IBIS,         exp: historical, ensemble: r1i1p1,  start_year: 1700,  end_year: 2019}
  - {model: JSBACH,   exp: historical, ensemble: r1i1p1,  start_year: 1700,  end_year: 2019}
  - {model: JULES-ES, exp: historical, ensemble: r1i1p1,  start_year: 1700,  end_year: 2019}
  - {model: LPX-Bern,  exp: historical, ensemble: r1i1p1,  start_year: 1700,  end_year: 2019}
  - {model: OCN,    exp: historical, ensemble: r1i1p1,  start_year: 1700,  end_year: 2019}
  - {model: ORCHIDEE-CNP,   exp: historical, ensemble: r1i1p1,  start_year: 1700,  end_year: 2019}
  - {model: ORCHIDEEv3, exp: historical, ensemble: r1i1p1,  start_year: 1700,  end_year: 2019}
  - {model: SDGVM,  exp: historical, ensemble: r1i1p1,  start_year: 1700,  end_year: 2019}
  - {model: VISIT,    exp: historical, ensemble: r1i1p1,  start_year: 1700,  end_year: 2019}

variables:
  - {name: cCwd,    frequency: month, unit: kg m-2}
  - {name: cLitter, frequency: month, unit: kg m-2}
  - {name: cSoil,   frequency: month, unit: kg m-2}
  - {name: cVeg,    frequency: month, unit: kg m-2}
  - {name: npp,     frequency: month, unit: kg m-2 s-1}
  - {name: gpp,     frequency: month, unit: kg m-2 s-1}
  - {name: tas,     frequency: month, unit: K}
  - {name: pr,      frequency: month, unit: kg m-2 s-1}

region:
  latmin: -90
  latmax: 90
  lonmin: -180
  lonmax: 180

path:
  inputDir: /mnt/f/ubuntu/Trendy/output #/mnt/i/TraceMe/dataSources/Model/download/historical #/mnt/e/MyWorks/traceME_offline/inputData 
  workRoot: /mnt/f/ubuntu/Trendy/output/workdir #/mnt/f/ubuntu/Works/TraceMe/TraceMe_workdir #/mnt/e/MyWorks/traceME_offline/TraceMe_workdir

script:
  TraceMeLand 