# TraceMe
# config.yml
---
documentation:
  description: |
    Test new version of TraceMe and run traceability analysis 

  authors:
    - zhou_jian

datasets:
  - {model: ACCESS-ESM1-5, exp: 1pctCO2-bgc, ensemble: r1i1p1,  start_year: 1850,  end_year: 1999} # 0101, 0250
  - {model: BCC-CSM2-MR,   exp: 1pctCO2-bgc, ensemble: r1i1p1,  start_year: 1850,  end_year: 1999}
  - {model: CanESM5,       exp: 1pctCO2-bgc, ensemble: r1i1p1,  start_year: 1850,  end_year: 2000}
  - {model: CESM2,         exp: 1pctCO2-bgc, ensemble: r1i1p1,  start_year: 1850,  end_year: 1999} # 0001, 0150
  - {model: CMCC-ESM2,     exp: 1pctCO2-bgc, ensemble: r1i1p1,  start_year: 1850,  end_year: 2014}
  - {model: GFDL-ESM4,     exp: 1pctCO2-bgc, ensemble: r1i1p1,  start_year: 1850,  end_year: 1999}
  - {model: IPSL-CM6A-LR,  exp: 1pctCO2-bgc, ensemble: r1i1p1,  start_year: 1850,  end_year: 1999}
  - {model: MIROC-ES2L,    exp: 1pctCO2-bgc, ensemble: r1i1p1,  start_year: 1850,  end_year: 1999}
  - {model: MPI-ESM1-2-LR, exp: 1pctCO2-bgc, ensemble: r1i1p1,  start_year: 1850,  end_year: 1989}
  - {model: MRI-ESM2-0,    exp: 1pctCO2-bgc, ensemble: r1i1p1,  start_year: 1850,  end_year: 2000}
  - {model: NorESM2-LM,    exp: 1pctCO2-bgc, ensemble: r1i1p1,  start_year: 1850,  end_year: 1989}
  - {model: UKESM1-0-LL,   exp: 1pctCO2-bgc, ensemble: r1i1p1,  start_year: 1850,  end_year: 1999}

variables:
  - {name: cCwd,    frequency: month, unit: kg m-2}
  - {name: cLitter, frequency: month, unit: kg m-2}
  - {name: cSoil,   frequency: month, unit: kg m-2}
  - {name: cVeg,    frequency: month, unit: kg m-2}
  - {name: npp,     frequency: month, unit: kg m-2 s-1}
  - {name: gpp,     frequency: month, unit: kg m-2 s-1}
  - {name: tas,     frequency: month, unit: K}
  - {name: pr,      frequency: month, unit: kg m-2 s-1}

region:
  latmin: -90
  latmax: 90
  lonmin: -180
  lonmax: 180

path:
  inputDir: /data_mpathfp1/home/zhou_j/TraceME_offline/TraceMe2_offline/inputData/runData_C4MIP/1pctCO2-bgc #/mnt/f/ubuntu/Works/C4MIP_testData #/mnt/c/ubuntu_docs/TraceME_offline/C4MIP_testData 
  workRoot: /data_mpathfp1/home/zhou_j/TraceME_offline/TraceMe2_offline/workDir/C4MIP_dir/1pctCO2-bgc #/mnt/c/ubuntu_docs/TraceME_offline/C4MIP_workDir 

analysis: # temporal analysis: default yes
  temporalAnalysis: yes
  spatialAnalysis: yes
  VegetationType: yes
  aboveAndBelowGround: yes

script:
  TraceMeLand 
